### PR TITLE
Remove link to Matt's blog.

### PR DESCRIPTION
**Pull request by mattbattison**
Remove link to my blog. Point to # instead for now.

### CODE REVIEW

**Comment by mattbattison** [comment]
Looks like it is working nicely though!

**Comment by tobiasduggan** [comment]
I didn't think it was working...

**Comment by mattbattison** [comment]
Sorry, yes. I mean the code is working okay. Not sure if the DNS is set up fully yet. I seem to be getting an infinite redirect if I go to the URL.

**Comment by mattbattison** [comment]
Yeah it looks like your domain is still pointing at GoDaddy. It should sort itself out in a few hours :)

**Comment by tobiasduggan** [comment]
Yeah I can't really see anything because my computer is a bit rubbish. I may have misspelled the domain when i did the dns but it won't let me change it until it's tried to link this one...

**Comment by tobiasduggan** [comment]
Ahh I removed the CNAME and it works now... I think with the CNAME it was trying to redirect from both ends making an infinite loop.

**Comment by mattbattison** [comment]
Nice! I think once it's all propagated though then you should be able to put the CNAME back in and then it'll actually show as tobiasduggan.com at the top instead of tobiasduggan.github.io

**Comment by mattbattison** [comment]
and thanks for the merge!

**Pull request merged**
